# Generated by Django 2.2.6 on 2019-10-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('descricao', models.TextField(max_length=1024, null=True, verbose_name='Descrição')),
                ('badge', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='badge.Badge')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaPreparacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('caracteristicas_etapa', models.ManyToManyField(default=None, null=True, to='produto.CaracteristicaEtapa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('descricao', models.TextField(max_length=1024, null=True)),
                ('composicao', models.ManyToManyField(null=True, related_name='_produto_composicao_+', to='produto.Produto')),
                ('etapas_preparacao', models.ManyToManyField(default=None, null=True, to='produto.EtapaPreparacao')),
            ],
        ),
    ]
