# Generated by Django 2.2.6 on 2019-10-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapapreparacao',
            name='caracteristicas_etapa',
            field=models.ManyToManyField(default=None, to='produto.CaracteristicaEtapa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='composicao',
            field=models.ManyToManyField(related_name='_produto_composicao_+', to='produto.Produto', verbose_name='Composição'),
        ),
    ]
