# Generated by Django 2.2.6 on 2019-10-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20191019_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='etapas_preparacao',
            field=models.ManyToManyField(default=None, to='produto.EtapaPreparacao'),
        ),
    ]
