# Generated by Django 2.2.6 on 2019-10-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20191019_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristicaetapa',
            options={'verbose_name': 'Característica da Etapa', 'verbose_name_plural': 'Características das Etapas'},
        ),
        migrations.AlterModelOptions(
            name='etapapreparacao',
            options={'verbose_name': 'Etapa de Preparação', 'verbose_name_plural': 'Etapas de Preparação'},
        ),
    ]
