# Generated by Django 2.2.6 on 2019-10-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0004_auto_20191019_1753'),
        ('produto', '0005_auto_20191019_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produtor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtor.Produtor'),
        ),
    ]
