# Generated by Django 2.2.6 on 2019-10-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_produto_produtor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas de Preparação',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('descricao', models.TextField(max_length=1024, null=True, verbose_name='Processos')),
            ],
            options={
                'verbose_name': 'Característica da Etapa',
                'verbose_name_plural': 'Características das Etapas',
            },
        ),
        migrations.RemoveField(
            model_name='etapapreparacao',
            name='caracteristicas_etapa',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='etapas_preparacao',
        ),
        migrations.DeleteModel(
            name='CaracteristicaEtapa',
        ),
        migrations.DeleteModel(
            name='EtapaPreparacao',
        ),
        migrations.AddField(
            model_name='metrica',
            name='processos',
            field=models.ManyToManyField(default=None, to='produto.Processo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='metricas',
            field=models.ManyToManyField(blank=True, default=None, to='produto.Metrica'),
        ),
    ]
