# Generated by Django 2.2.6 on 2019-10-19 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0007_auto_20191019_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={},
        ),
        migrations.AddField(
            model_name='produto',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao',
            field=models.TextField(max_length=1024, null=True, verbose_name='Descrição'),
        ),
    ]
