# Generated by Django 2.2.6 on 2019-10-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_auto_20191019_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='url_imagem',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
