# Generated by Django 2.2.6 on 2019-10-19 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0009_metrica_url_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrica',
            options={'verbose_name': 'Métrica', 'verbose_name_plural': 'Métricas'},
        ),
        migrations.AddField(
            model_name='metrica',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
