# Generated by Django 2.2.6 on 2019-10-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_auto_20191019_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='url_imagem',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
