# Generated by Django 2.2.6 on 2019-10-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_produto_url_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('data', models.DateField()),
                ('produtor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.Produto')),
            ],
        ),
    ]
