# Generated by Django 2.2.6 on 2019-10-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_lote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='produtor',
            new_name='produto',
        ),
    ]
