# Generated by Django 2.2.6 on 2019-10-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_lote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='url_imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='url_imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
