# Generated by Django 2.2.6 on 2019-10-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_auto_20191019_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='composto',
            field=models.ManyToManyField(blank=True, related_name='_lote_composto_+', to='produto.Lote', verbose_name='Composto por'),
        ),
    ]
