# Generated by Django 2.2.6 on 2019-10-19 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0018_auto_20191019_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('lote', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.Lote')),
                ('processo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.Processo')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
