# Generated by Django 2.2.6 on 2019-10-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0019_historicolote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicolote',
            options={'verbose_name': 'Histórico do Lote', 'verbose_name_plural': 'Histórico dos Lotes'},
        ),
    ]
