# Generated by Django 2.2.6 on 2019-10-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtor',
            name='produtos',
            field=models.ManyToManyField(blank=True, default=None, to='produtor.Produtor'),
        ),
    ]
