# Generated by Django 2.2.6 on 2019-10-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0002_auto_20191019_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterModelOptions(
            name='produtor',
            options={'verbose_name_plural': 'Produtores'},
        ),
        migrations.AlterField(
            model_name='produtor',
            name='produtos',
            field=models.ManyToManyField(blank=True, default=None, to='produto.Produto'),
        ),
    ]
