# Generated by Django 2.2.6 on 2019-10-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0003_auto_20191019_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtor',
            name='produtos',
            field=models.ManyToManyField(blank=True, default=None, related_name='produtor_produtos', to='produto.Produto'),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='tipo',
            field=models.IntegerField(choices=[(10, 'Campo'), (20, 'Industria'), (30, 'Restaurante')], default=None),
        ),
    ]
