# Generated by Django 2.2.6 on 2019-10-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0004_auto_20191019_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtor',
            name='produtos',
        ),
    ]
