# Generated by Django 2.2.6 on 2019-10-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0005_remove_produtor_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtor',
            name='descricao',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Descrição'),
        ),
    ]
