# Generated by Django 2.2.6 on 2019-10-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('descricao', models.TextField(max_length=1024, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='upload/badges', verbose_name='Selecione a imagem')),
            ],
        ),
    ]
